--
-- PostgreSQL database dump
--

\restrict gWiDKdoPd4WBoPbTUSVR7Y22xNmwFcv477o9fefGd3S46ZE9JlHyolOP6pzxiRu

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cla; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cla (
    id_cla bigint NOT NULL,
    descricao_cla character varying(255) NOT NULL,
    habilidade_cla character varying(255) NOT NULL,
    nome_cla character varying(50) NOT NULL
);


ALTER TABLE public.cla OWNER TO postgres;

--
-- Name: cla_id_cla_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cla ALTER COLUMN id_cla ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cla_id_cla_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ninja; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ninja (
    id_ninja bigint NOT NULL,
    cpf_ninja character varying(255) NOT NULL,
    email_ninja character varying(255) NOT NULL,
    nome_ninja character varying(50) NOT NULL
);


ALTER TABLE public.ninja OWNER TO postgres;

--
-- Name: ninja_id_ninja_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ninja ALTER COLUMN id_ninja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ninja_id_ninja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ninja_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ninja_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ninja_seq OWNER TO postgres;

--
-- Data for Name: cla; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cla (id_cla, descricao_cla, habilidade_cla, nome_cla) FROM stdin;
\.


--
-- Data for Name: ninja; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ninja (id_ninja, cpf_ninja, email_ninja, nome_ninja) FROM stdin;
1	123.456.789-0	narutinhoReidelas@viladafoha.com.br	Naruto Uzumali
\.


--
-- Name: cla_id_cla_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cla_id_cla_seq', 6, true);


--
-- Name: ninja_id_ninja_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ninja_id_ninja_seq', 1, false);


--
-- Name: ninja_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ninja_seq', 1, true);


--
-- Name: cla cla_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cla
    ADD CONSTRAINT cla_pkey PRIMARY KEY (id_cla);


--
-- Name: ninja ninja_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ninja
    ADD CONSTRAINT ninja_pkey PRIMARY KEY (id_ninja);


--
-- Name: ninja ukaplh6a8mmusxrj6h9q2m56g0x; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ninja
    ADD CONSTRAINT ukaplh6a8mmusxrj6h9q2m56g0x UNIQUE (email_ninja);


--
-- Name: ninja ukq5kn2w4dyxc5sqg1txi2206sm; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ninja
    ADD CONSTRAINT ukq5kn2w4dyxc5sqg1txi2206sm UNIQUE (cpf_ninja);


--
-- PostgreSQL database dump complete
--

\unrestrict gWiDKdoPd4WBoPbTUSVR7Y22xNmwFcv477o9fefGd3S46ZE9JlHyolOP6pzxiRu

