spring.application.name=ninjas
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas
spring.datasource.username=postgres
spring.datasource.password=123456


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.separator=^^


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true