DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'ninja'
          AND column_name = 'id_ninja'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        ALTER TABLE ninja
            ALTER COLUMN id_ninja ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$^^
